export type CompoundKind = 'natural' | 'semi-synthetic' | 'synthetic'

export type CatalogProduct = {
  id: string
  name: string
  kind: CompoundKind
  strength: string
  use: string
  contraindications: string
  sideEffects: string
}

export type CatalogCategory = {
  id: string
  title: string
  blurb: string
  products: CatalogProduct[]
}

/** Compounded Rx formulary sourced from the practitioner sales sheet. */
export const COMPOUNDED_CATALOG: CatalogCategory[] = [
  {
    id: 'glp1',
    title: 'GLP-1 & Weight Management',
    blurb: 'Injectable and sublingual GLP-1 / dual / triple agonist therapies for metabolic care.',
    products: [
      {
        id: 'sema-gly',
        name: 'Semaglutide + Glycine',
        kind: 'synthetic',
        strength: '2.5 | 5 | 12.5 mg vials · Weekly SC',
        use: 'Starter through maintenance weight-management protocols.',
        contraindications: 'Active/personal hx of MTC or MEN2, pancreatitis, severe renal impairment, pregnancy.',
        sideEffects: 'Nausea, vomiting, diarrhea, constipation, injection-site reactions, tachycardia.',
      },
      {
        id: 'sema-b12',
        name: 'Semaglutide + B12',
        kind: 'synthetic',
        strength: '2.5 | 5 | 12.5 mg vials · Weekly SC',
        use: 'B12-enhanced GLP-1 with improved tolerability focus.',
        contraindications: 'Same as Semaglutide; caution with metformin (B12 absorption).',
        sideEffects: 'Same as Semaglutide; B12 may cause mild flushing or acne in high doses.',
      },
      {
        id: 'tirz',
        name: 'Tirzepatide Injectable',
        kind: 'synthetic',
        strength: '18 | 36 | 72 mg vials · Weekly SC',
        use: 'Dual GIP/GLP-1 — potent metabolic therapy.',
        contraindications: 'MTC/MEN2 history, pancreatitis, severe GI disease, pregnancy.',
        sideEffects: 'Nausea, vomiting, diarrhea, reduced appetite, injection-site reactions, hypoglycemia (w/ insulin).',
      },
      {
        id: 'tirz-b12',
        name: 'Tirzepatide + B12',
        kind: 'synthetic',
        strength: '17 | 34 | 68 mg vials · Weekly SC',
        use: 'Energy-enhanced dual-agonist protocols.',
        contraindications: 'Same as Tirzepatide.',
        sideEffects: 'Same as Tirzepatide; B12 flushing.',
      },
      {
        id: 'reta',
        name: 'Retatrutide (R3-40)',
        kind: 'synthetic',
        strength: '40 mg pen | 10 mg vial',
        use: 'Triple agonist: GLP-1 + GIP + Glucagon.',
        contraindications: 'MTC/MEN2, pancreatitis, hepatic impairment; limited long-term data.',
        sideEffects: 'Nausea, vomiting, diarrhea, reduced appetite, potential HR elevation.',
      },
      {
        id: 'sema-sl',
        name: 'Sublingual Semaglutide',
        kind: 'synthetic',
        strength: '2–10 mg / 8 mL · 5 strengths',
        use: 'Needle-free GLP-1 option.',
        contraindications: 'Same as injectable Semaglutide; reduced bioavailability vs. SC.',
        sideEffects: 'Oral mucosal irritation, GI effects, nausea.',
      },
      {
        id: 'tirz-sl',
        name: 'Sublingual Tirzepatide',
        kind: 'synthetic',
        strength: '5–30 mg / 8 mL · 6 strengths',
        use: 'Needle-free dual agonist.',
        contraindications: 'Same as injectable Tirzepatide.',
        sideEffects: 'Oral mucosal irritation, GI effects.',
      },
      {
        id: 'tirz-nad',
        name: 'Sublingual Tirzepatide + NAD+',
        kind: 'synthetic',
        strength: '5–17.5 mg + 100 mg NAD+ / 8 mL',
        use: 'GLP-1 + cellular energy combined.',
        contraindications: 'Same as Tirzepatide; caution with active vasodilatory conditions (NAD+).',
        sideEffects: 'GI effects, flushing (NAD+), headache.',
      },
    ],
  },
  {
    id: 'nad',
    title: 'NAD+ & Longevity',
    blurb: 'Cellular energy, antioxidant, and telomere-support compounds.',
    products: [
      {
        id: 'nad-600',
        name: 'NAD+ 600 mg Pen',
        kind: 'natural',
        strength: '200 mg/mL · 3 mL pen · SC 2–3×/wk',
        use: 'Energy & cognition support.',
        contraindications: 'Active malignancy (theoretical), pregnancy; caution with PARP inhibitors.',
        sideEffects: 'Flushing, nausea, headache, injection-site discomfort, transient fatigue.',
      },
      {
        id: 'nad-1000',
        name: 'NAD+ 1000 mg Pen',
        kind: 'natural',
        strength: '333 mg/mL · 3 mL pen',
        use: 'High-dose advanced cellular repair.',
        contraindications: 'Same as 600 mg pen; titrate slowly.',
        sideEffects: 'Stronger flushing, headache, GI discomfort at high doses.',
      },
      {
        id: 'nad-vial',
        name: 'NAD+ 1000/1200 mg Vial',
        kind: 'natural',
        strength: '100–200 mg/mL · 6–10 mL · IV/IM',
        use: 'Longevity drip protocol.',
        contraindications: 'Hypotension, active cardiac arrhythmia (rapid IV), pregnancy.',
        sideEffects: 'Chest tightness, flushing, nausea during infusion; slow IV rate.',
      },
      {
        id: 'gsh',
        name: 'Glutathione 2000 mg',
        kind: 'natural',
        strength: '200 mg/mL · 10 mL vial · IV push',
        use: 'Brightening + antioxidant support.',
        contraindications: 'Asthma (inhaled form), chemotherapy patients.',
        sideEffects: 'Rare bronchospasm; bloating; zinc depletion with prolonged use.',
      },
      {
        id: 'b12',
        name: 'Methylcobalamin B12',
        kind: 'natural',
        strength: '1 mg/mL · 10 mL vial',
        use: 'Active B12; neuro + methylation.',
        contraindications: "Leber's disease, cobalt hypersensitivity.",
        sideEffects: 'Rare: acne, itching, mild diarrhea.',
      },
      {
        id: 'epithalon',
        name: 'Epithalon',
        kind: 'synthetic',
        strength: '2 mg/mL · 5 mL | 10 mg vial',
        use: 'Telomerase activation; anti-aging.',
        contraindications: 'Active malignancy, pregnancy; limited clinical data.',
        sideEffects: 'Generally well tolerated; mild injection-site reactions.',
      },
      {
        id: 'ta1',
        name: 'Thymosin A-1 (TA-1)',
        kind: 'semi-synthetic',
        strength: '1 mg/mL · 5 mL | 10 mg vial',
        use: 'Immune modulation; anti-viral support.',
        contraindications: 'Autoimmune disease, organ transplant recipients.',
        sideEffects: 'Injection-site reactions, mild fatigue, rare flu-like symptoms.',
      },
      {
        id: 'ss31',
        name: 'SS-31 | Lipo-B',
        kind: 'synthetic',
        strength: '10–50 mg | 50/50/25/1 mg/mL',
        use: 'Mitochondrial + lipotropic support.',
        contraindications: 'Limited clinical data; caution in severe renal/hepatic disease.',
        sideEffects: 'Mild injection-site reactions; GI upset (Lipo-B).',
      },
    ],
  },
  {
    id: 'gh',
    title: 'Growth Hormone & Performance',
    blurb: 'GH secretagogues and metabolic fragments for body composition.',
    products: [
      {
        id: 'sermorelin',
        name: 'Sermorelin',
        kind: 'semi-synthetic',
        strength: '3 mg/mL · 5 mL | pens',
        use: 'Nightly GH; lean mass & fat loss.',
        contraindications: 'Active malignancy, hypothyroidism, pituitary disorders, pregnancy.',
        sideEffects: 'Injection-site reactions, flushing, headache, fluid retention, joint pain.',
      },
      {
        id: 'tesamorelin',
        name: 'Tesamorelin',
        kind: 'semi-synthetic',
        strength: '3 mg/mL · 5 mL | pens',
        use: 'Visceral fat reduction; IGF-1 stimulation.',
        contraindications: 'Active malignancy, pregnancy, pituitary disease; caution in diabetes.',
        sideEffects: 'Peripheral edema, arthralgia, injection-site reactions, glucose elevation.',
      },
      {
        id: 'tesa-ipa',
        name: 'Tesamorelin + Ipamorelin',
        kind: 'semi-synthetic',
        strength: '3 mg/2 mg per mL · 5 mL',
        use: 'GH secretagogue synergy stack.',
        contraindications: 'Same as Tesamorelin; monitor IGF-1.',
        sideEffects: 'Fluid retention, joint pain, injection-site reactions, headache.',
      },
      {
        id: 'cjc-ipa',
        name: 'CJC-1295 + Ipamorelin',
        kind: 'semi-synthetic',
        strength: '1.2/2 mg per mL · 5 mL | pen',
        use: 'GH pulse optimization; body composition.',
        contraindications: 'Active malignancy, uncontrolled diabetes, pregnancy.',
        sideEffects: 'Water retention, tingling/numbness, headache, injection-site reactions.',
      },
      {
        id: 'aod',
        name: 'AOD-9604',
        kind: 'semi-synthetic',
        strength: '1.2 mg/mL · 5 mL vial',
        use: 'GH fragment; fat lipolysis only.',
        contraindications: 'Pregnancy; limited long-term human data.',
        sideEffects: 'Injection-site reactions, headache; generally well tolerated.',
      },
      {
        id: 'aod-mots',
        name: 'AOD-9604 + MOTS-C',
        kind: 'semi-synthetic',
        strength: '1.2/2 mg per mL · 5 mL',
        use: 'Fat oxidation + mitochondrial metabolism.',
        contraindications: 'Pregnancy; caution in diabetes.',
        sideEffects: 'Injection-site reactions, fatigue, GI discomfort.',
      },
      {
        id: 'mk677',
        name: 'Ibutamoren MK-677',
        kind: 'synthetic',
        strength: '25 mg oral capsule',
        use: 'Oral GH secretagogue; deep sleep support.',
        contraindications: 'Active malignancy, pre-existing edema/CHF, uncontrolled diabetes.',
        sideEffects: 'Water retention, increased appetite, joint pain, elevated blood glucose.',
      },
    ],
  },
  {
    id: 'repair',
    title: 'Tissue Repair & Recovery',
    blurb: 'Healing peptides and regenerative blends for soft tissue and skin.',
    products: [
      {
        id: 'wolverine',
        name: 'Wolverine Blend Pen',
        kind: 'semi-synthetic',
        strength: 'BPC-157 + TB-500 · 10/10 mg',
        use: 'Soft tissue & mobility recovery.',
        contraindications: 'Active malignancy, pregnancy; limited long-term data.',
        sideEffects: 'Injection-site reactions, nausea (BPC-157), mild fatigue.',
      },
      {
        id: 'recovery',
        name: 'Recovery Blend Pen',
        kind: 'semi-synthetic',
        strength: 'BPC-157 + TB-500 + GHK-Cu + KPV',
        use: 'Full-spectrum healing + collagen.',
        contraindications: 'Active malignancy, pregnancy.',
        sideEffects: 'Injection-site reactions, nausea, possible fatigue, skin flushing.',
      },
      {
        id: 'glow',
        name: 'Glow Blend Pen',
        kind: 'semi-synthetic',
        strength: 'BPC-157 + TB-500 + GHK-Cu',
        use: 'Skin, collagen & tissue repair.',
        contraindications: 'Active malignancy, pregnancy.',
        sideEffects: 'Injection-site reactions, transient skin warmth/redness.',
      },
      {
        id: 'bpc-tb',
        name: 'BPC-157 + TB-500',
        kind: 'semi-synthetic',
        strength: '3/3 mg per mL · 5 mL | vials',
        use: 'Accelerated tissue & injury repair.',
        contraindications: 'Active malignancy, pregnancy; caution post-surgery.',
        sideEffects: 'Nausea, dizziness, injection-site reactions.',
      },
      {
        id: 'ghk',
        name: 'GHK-Cu',
        kind: 'natural',
        strength: '10 mg/mL · 5 mL | 50 mg | pen',
        use: 'Copper peptide; collagen & skin healing.',
        contraindications: "Wilson's disease, copper allergy.",
        sideEffects: 'Skin irritation at application site, transient redness.',
      },
      {
        id: 'klow',
        name: 'KLOW (BPC + GHK + KPV + TB)',
        kind: 'semi-synthetic',
        strength: '3/10/3/3 mg per mL · 5 mL',
        use: 'Full-spectrum regenerative protocol.',
        contraindications: 'Active malignancy, pregnancy; multi-peptide profile limited.',
        sideEffects: 'Injection-site reactions, fatigue, GI discomfort.',
      },
    ],
  },
  {
    id: 'hormone',
    title: 'Hormonal Health & Sexual Wellness',
    blurb: 'Reproductive, libido, cognitive, and metabolic peptide protocols.',
    products: [
      {
        id: 'gonadorelin',
        name: 'Gonadorelin | Kisspeptin',
        kind: 'natural',
        strength: '1 mg/mL · 5 mL vials',
        use: 'GnRH + reproductive hormone support.',
        contraindications: 'Hormone-sensitive cancers, pregnancy, uncontrolled pituitary disorders.',
        sideEffects: 'Headache, nausea, injection-site reactions.',
      },
      {
        id: 'pt141',
        name: 'PT-141 (Bremelanotide)',
        kind: 'semi-synthetic',
        strength: '2 mg/mL · 5 mL | 10–20 mg pens',
        use: 'CNS libido agonist; max 8×/month.',
        contraindications: 'CV disease, uncontrolled hypertension, pregnancy; do NOT use with nitrates.',
        sideEffects: 'Nausea, flushing, headache, transient hypertension.',
      },
      {
        id: 'mots',
        name: 'MOTS-C',
        kind: 'natural',
        strength: '2 mg/mL · 5 mL | 20–25 mg pens',
        use: 'AMPK activation; metabolic flexibility.',
        contraindications: 'Limited human data; caution in diabetes.',
        sideEffects: 'Injection-site reactions, mild fatigue, hypoglycemia risk.',
      },
      {
        id: 'igf',
        name: 'IGF-LR3',
        kind: 'semi-synthetic',
        strength: '200 mcg/mL · 5 mL vial',
        use: 'Muscle growth; anabolic signaling.',
        contraindications: 'Active malignancy, diabetic retinopathy, pregnancy.',
        sideEffects: 'Hypoglycemia, headache, jaw/hand pain, water retention.',
      },
      {
        id: 'semax-selank',
        name: 'Semax | Selank',
        kind: 'semi-synthetic',
        strength: '10 mg vials | combo 1/1 mg/mL',
        use: 'Cognitive clarity + anxiolytic balance.',
        contraindications: 'Seizure disorder, pregnancy; limited Western data.',
        sideEffects: 'Nasal irritation, mild anxiety or sedation, headache.',
      },
      {
        id: 'dsip',
        name: 'DSIP',
        kind: 'natural',
        strength: '1 mg/mL · 5 mL | 5 mg pen',
        use: 'Sleep neuropeptide; 30–60 min before bed.',
        contraindications: 'Pregnancy; sleep apnea (monitor).',
        sideEffects: 'Drowsiness, dizziness, headache.',
      },
      {
        id: 'ondansetron',
        name: 'Ondansetron 4 mg',
        kind: 'synthetic',
        strength: 'Oral tablet (Rx)',
        use: 'Anti-nausea; GLP-1 tolerability support.',
        contraindications: 'QT prolongation, hypokalemia/hypomagnesemia, serotonin syndrome risk.',
        sideEffects: 'Headache, constipation, QT prolongation.',
      },
    ],
  },
]

export const KIND_LABEL: Record<CompoundKind, string> = {
  natural: 'Natural',
  'semi-synthetic': 'Semi-synthetic',
  synthetic: 'Synthetic',
}
