export type Product = {
  /** LUMIDOR order-form product number */
  no: number;
  sku: string;
  name: string;
  spec: string;
  /** Suggested online retail */
  online: number;
  /** Manufacturer suggested retail */
  msrp: number;
  /** SPA / practice wholesale cost (order price) */
  price: number;
  info: string;
};

export type Group = { title: string; blurb: string; items: Product[] };

/** Full LUMIDOR / Abio Materials order sheet — Online · MSRP · SPA. */
export const catalog: Group[] = [
  {
    title: "SX Series — Stem Rejuvenation",
    blurb:
      "Human-derived exosomes. A stem-cell rejuvenation regimen designed to brighten, firm and restore elasticity in mature or photo-aged skin.",
    items: [
      {
        no: 1,
        sku: "LD-01",
        name: "SX STEM Solution Ampoules",
        spec: "6 ml × 12 vials",
        online: 187,
        msrp: 175,
        price: 85,
        info: "Concentrated stem-cell conditioned media ampoules used in-clinic post-microneedling, RF or laser to accelerate recovery and boost collagen signaling.",
      },
      {
        no: 2,
        sku: "LD-02",
        name: "SX Rejuv Toner",
        spec: "200 ml",
        online: 75,
        msrp: 70,
        price: 35,
        info: "Hydrating prep toner that balances skin pH and primes the barrier to absorb the SX serum and cream.",
      },
      {
        no: 3,
        sku: "LD-03",
        name: "SX Rejuv Serum",
        spec: "50 ml",
        online: 110,
        msrp: 100,
        price: 50,
        info: "Lightweight stem-cell extract serum targeting fine lines, dullness and uneven tone for at-home daily use.",
      },
      {
        no: 4,
        sku: "LD-04",
        name: "SX Rejuv Cream",
        spec: "50 ml",
        online: 130,
        msrp: 120,
        price: 57.5,
        info: "Rich moisturizer that seals in actives, supports the lipid barrier and improves overnight skin density.",
      },
      {
        no: 23,
        sku: "LD-23",
        name: "SX Rejuv EXO Shampoo",
        spec: "500 ml",
        online: 85,
        msrp: 76,
        price: 38,
        info: "Daily exosome shampoo supporting follicle health and a balanced scalp microbiome.",
      },
      {
        no: 25,
        sku: "LD-25",
        name: "SX Rejuv EXO Treatment",
        spec: "500 ml",
        online: 85,
        msrp: 76,
        price: 38,
        info: "Weekly exosome treatment that strengthens the hair shaft and improves density over time.",
      },
    ],
  },
  {
    title: "PX Series — Refine & Restore",
    blurb:
      "Plant-derived exosomes. A refining system for daily aesthetic protocols — pore refinement, oil balance and gentle calming.",
    items: [
      {
        no: 6,
        sku: "LD-06",
        name: "PX Solution Ampoules",
        spec: "6 ml × 12 vials",
        online: 154,
        msrp: 150,
        price: 75,
        info: "In-clinic ampoules with refining peptides — pairs with microneedling for pore size, texture and post-acne marks.",
      },
      {
        no: 7,
        sku: "LD-07",
        name: "PX Refine Toner",
        spec: "200 ml",
        online: 55,
        msrp: 46,
        price: 23,
        info: "Mild astringent toner that tightens pores and removes residual impurities after cleansing.",
      },
      {
        no: 8,
        sku: "LD-08",
        name: "PX Refine Serum",
        spec: "50 ml",
        online: 80,
        msrp: 70,
        price: 35,
        info: "Pore-refining serum with niacinamide-style actives to balance sebum and even tone.",
      },
      {
        no: 9,
        sku: "LD-09",
        name: "PX Refine Cream",
        spec: "50 ml",
        online: 88,
        msrp: 70,
        price: 35,
        info: "Non-comedogenic moisturizer for combination and oily skin types — lightweight, hydrating, matte finish.",
      },
      {
        no: 11,
        sku: "LD-11",
        name: "PX BIO Water Soothing MIST",
        spec: "100 ml",
        online: 53,
        msrp: 40,
        price: 20,
        info: "Calming bio-water mist used to soothe reactive skin during or after in-clinic treatments.",
      },
      {
        no: 20,
        sku: "LD-20",
        name: "PX Refine Cleansing GEL",
        spec: "250 ml",
        online: 50,
        msrp: 45,
        price: 30,
        info: "Sulfate-free gel cleanser for face — removes makeup, sebum and impurities without stripping the barrier.",
      },
      {
        no: 21,
        sku: "LD-21",
        name: "PX Refine BODY Cleanser",
        spec: "400 ml",
        online: 50,
        msrp: 45,
        price: 30,
        info: "Body cleanser formulated for sensitive and post-procedure body skin.",
      },
    ],
  },
  {
    title: "Skin Booster",
    blurb: "Refine Shot skin boosters for in-clinic exfoliation and renewal protocols.",
    items: [
      {
        no: 12,
        sku: "LD-12",
        name: "Refine SHOT SKIN BOOSTER 30000",
        spec: "3 ml",
        online: 70,
        msrp: 60,
        price: 30,
        info: "High-density spicule shot for in-clinic exfoliation and skin renewal — strong turnover, single-session results.",
      },
      {
        no: 13,
        sku: "LD-13",
        name: "Refine SHOT SKIN BOOSTER 2000",
        spec: "50 ml",
        online: 50,
        msrp: 40,
        price: 20,
        info: "Lower-density maintenance spicule formula for facials and gentler skin renewal protocols.",
      },
      {
        no: 40,
        sku: "LD-40",
        name: "Celexo Refine Shot Skin Booster 30000",
        spec: "3 ml × 5 vials / 1 box",
        online: 350,
        msrp: 300,
        price: 140,
        info: "Clinic multi-pack of high-density Refine Shot Skin Booster 30000 — five vials per box.",
      },
    ],
  },
  {
    title: "Spicule Series — Microchannel Activation",
    blurb:
      "Botanical spicules create micro-channels in the stratum corneum, allowing actives to penetrate without needles.",
    items: [
      {
        no: 14,
        sku: "LD-14",
        name: "EXO Activation SX Spicule Cream",
        spec: "30 ml",
        online: 88,
        msrp: 80,
        price: 40,
        info: "Spicule + exosome activation cream for rejuvenation protocols — drives SX actives deeper into the dermis.",
      },
      {
        no: 15,
        sku: "LD-15",
        name: "EXO Activation CICA Spicule Cream",
        spec: "30 ml",
        online: 80,
        msrp: 72,
        price: 36,
        info: "Centella-based calming spicule cream for sensitized, post-procedure or rosacea-prone skin.",
      },
      {
        no: 16,
        sku: "LD-16",
        name: "EXO Activation LACTO Spicule Cream",
        spec: "30 ml",
        online: 80,
        msrp: 72,
        price: 36,
        info: "Lactobacillus-fermented spicule cream for barrier repair and microbiome support.",
      },
    ],
  },
  {
    title: "Creams",
    blurb: "Post-procedure, lifting and recovery creams featuring exosome technology.",
    items: [
      {
        no: 17,
        sku: "LD-17",
        name: "Soothing BOOSTER Cream",
        spec: "100 ml",
        online: 66,
        msrp: 60,
        price: 30,
        info: "Calming, anti-inflammatory cream used immediately post-treatment to reduce erythema and discomfort.",
      },
      {
        no: 18,
        sku: "LD-18",
        name: "Lifting EXO Cream",
        spec: "100 ml",
        online: 120,
        msrp: 114,
        price: 57,
        info: "Exosome-enriched firming cream that improves elasticity, jawline definition and skin density with daily use.",
      },
      {
        no: 19,
        sku: "LD-19",
        name: "CellExosome After Care Cream",
        spec: "50 ml",
        online: 80,
        msrp: 70,
        price: 35,
        info: "Take-home recovery cream for patients following microneedling, peels, RF or laser — promotes barrier recovery.",
      },
      {
        no: 42,
        sku: "LD-42",
        name: "Celexo Post Care Calming Cream",
        spec: "100 ml",
        online: 110,
        msrp: 100,
        price: 50,
        info: "Post-care calming cream to soothe erythema and support barrier recovery after aesthetic procedures.",
      },
      {
        no: 43,
        sku: "LD-43",
        name: "Celexo Post Care Recovery Cream",
        spec: "50 ml",
        online: 70,
        msrp: 60,
        price: 30,
        info: "Recovery cream formulated for take-home use after in-clinic exosome and device treatments.",
      },
    ],
  },
  {
    title: "Cleansers",
    blurb: "Prep cleansers, toners and washes used to start facial and scalp protocols.",
    items: [
      {
        no: 22,
        sku: "LD-22",
        name: "Celexo AAPE Hair Scaler",
        spec: "200 ml",
        online: 70,
        msrp: 60,
        price: 30,
        info: "Scalp scaler that exfoliates buildup and prepares the scalp for AAPE and exosome treatments.",
      },
      {
        no: 39,
        sku: "LD-39",
        name: "Celexo Refine Bubble Toner",
        spec: "300 ml",
        online: 110,
        msrp: 100,
        price: 50,
        info: "Bubble toner that gently cleanses and refinishes skin before exosome or spicule protocols.",
      },
      {
        no: 38,
        sku: "LD-38",
        name: "Celexo Enzyme Powder Wash",
        spec: "80 g",
        online: 110,
        msrp: 100,
        price: 50,
        info: "Enzyme powder wash for enzymatic exfoliation and prep before aesthetic treatments.",
      },
    ],
  },
  {
    title: "Hair",
    blurb: "Scalp and hair restoration line for trichology and aesthetic medicine.",
    items: [
      {
        no: 24,
        sku: "LD-24",
        name: "EXO STEM Hair TONIC",
        spec: "100 ml",
        online: 70,
        msrp: 60,
        price: 30,
        info: "Leave-on stem-cell tonic for thinning hair — used between in-clinic treatments to extend results.",
      },
      {
        no: 44,
        sku: "LD-44",
        name: "Celexo Solution Shampoo",
        spec: "500 ml",
        online: 90,
        msrp: 80,
        price: 40,
        info: "Daily solution shampoo supporting scalp balance and hair density programs.",
      },
      {
        no: 45,
        sku: "LD-45",
        name: "Celexo Solution Treatment",
        spec: "500 ml",
        online: 90,
        msrp: 80,
        price: 38,
        info: "Weekly solution treatment masque to strengthen the hair shaft and improve manageability.",
      },
      {
        no: 46,
        sku: "LD-46",
        name: "Celexo Solution Scalp Scaler",
        spec: "200 ml",
        online: 80,
        msrp: 70,
        price: 35,
        info: "Scalp scaler that clears buildup ahead of tonic and in-clinic hair protocols.",
      },
      {
        no: 47,
        sku: "LD-47",
        name: "Celexo Solution Hair Tonic",
        spec: "100 ml",
        online: 80,
        msrp: 70,
        price: 35,
        info: "Leave-on hair tonic for daily scalp support between professional treatments.",
      },
    ],
  },
  {
    title: "Celexo EXO Therapy",
    blurb:
      "Lyophilized exosome and AAPE skin and hair boosters for in-clinic professional use only.",
    items: [
      {
        no: 26,
        sku: "LD-26",
        name: "Celexo Black Label Skin",
        spec: "Powder: 30 mg / Solvent: 4 ml",
        online: 190,
        msrp: 180,
        price: 90,
        info: "Premium lyophilized exosome skin booster — flagship formula for anti-aging, glow and post-laser recovery.",
      },
      {
        no: 27,
        sku: "LD-27",
        name: "CellExosome Black Label Skin",
        spec: "Powder: 30 mg / Solvent: 4 ml",
        online: 176,
        msrp: 160,
        price: 80,
        info: "CellExosome Black Label skin booster for professional rejuvenation and recovery protocols.",
      },
      {
        no: 28,
        sku: "LD-28",
        name: "CellExosome Black Label Hair",
        spec: "Powder: 30 mg / Solvent: 4 ml",
        online: 176,
        msrp: 160,
        price: 80,
        info: "Premium exosome hair booster for androgenic alopecia, post-PRP combination protocols and hair density.",
      },
      {
        no: 29,
        sku: "LD-29",
        name: "Celexo S",
        spec: "Powder: 200 mg / Solvent: 6 ml",
        online: 154,
        msrp: 140,
        price: 70,
        info: "High-volume exosome booster designed for larger treatment areas — neck, décolleté, hands and body.",
      },
      {
        no: 30,
        sku: "LD-30",
        name: "Celexo HG",
        spec: "2 Syringes",
        online: 330,
        msrp: 300,
        price: 150,
        info: "Pre-mixed syringe format of the HG booster — ready to use, ideal for fast in-clinic protocols.",
      },
      {
        no: 31,
        sku: "LD-31",
        name: "Celexo (10 vial)",
        spec: "3 ml × 10 vials",
        online: 800,
        msrp: 700,
        price: 350,
        info: "Multi-patient pack — 10-vial value pack of the core Celexo exosome booster for high-volume clinics.",
      },
      {
        no: 32,
        sku: "LD-32",
        name: "Celexo (2 vial)",
        spec: "3 ml × 2 vials",
        online: 180,
        msrp: 160,
        price: 80,
        info: "Trial / single-patient pack of the Celexo exosome booster.",
      },
      {
        no: 33,
        sku: "LD-33",
        name: "AAPE Skin",
        spec: "Powder: 290 mg / Solvent: 6 ml (6 sets)",
        online: 660,
        msrp: 600,
        price: 300,
        info: "Six-set pack of AAPE (Advanced Adipose-derived stem cell Protein Extract) for skin rejuvenation programs.",
      },
      {
        no: 34,
        sku: "LD-34",
        name: "AAPE Hair",
        spec: "Powder: 290 mg / Solvent: 6 ml (6 sets)",
        online: 660,
        msrp: 600,
        price: 300,
        info: "Six-set pack of AAPE for scalp and hair restoration treatment series.",
      },
      {
        no: 41,
        sku: "LD-41",
        name: "Celexo Bio Solution Ampoule",
        spec: "6 ml × 5 vial / 1 box",
        online: 170,
        msrp: 160,
        price: 80,
        info: "Bio solution ampoule multi-pack for in-clinic regenerative aesthetic protocols.",
      },
    ],
  },
  {
    title: "Mask",
    blurb: "In-clinic energizing, sealing and micro-current treatment masks.",
    items: [
      {
        no: 35,
        sku: "LD-35",
        name: "LuciDor Energetic Galvanic Gold Mask",
        spec: "6 Masks + 6 Batteries",
        online: 150,
        msrp: 100,
        price: 50,
        info: "Self-powered galvanic gold mask that drives serums deeper, brightens and visibly lifts — perfect treatment finisher.",
      },
      {
        no: 36,
        sku: "LD-36",
        name: "Celexo Hydro Sealing Mask",
        spec: "10 masks",
        online: 110,
        msrp: 100,
        price: 50,
        info: "Hydro sealing sheet mask that locks in actives and hydrates after in-clinic treatments.",
      },
      {
        no: 37,
        sku: "LD-37",
        name: "Celexo Galvanic Micro-Current Mask",
        spec: "10 Masks + 10 Batteries",
        online: 150,
        msrp: 140,
        price: 70,
        info: "Galvanic micro-current mask for lifting, firming and enhanced serum delivery chairside.",
      },
    ],
  },
];

export const allItems: Product[] = catalog.flatMap((g) => g.items);
