/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExosomesRouteImport } from './routes/exosomes'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrescribersRouteImport } from './routes/prescribers'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiPublicAgeConfirmRouteImport } from './routes/api/public/age-confirm'
import { Route as ApiEmailQueueProcessRouteImport } from './routes/api/email/queue/process'
import { Route as ApiEmailWebhooksResendRouteImport } from './routes/api/email/webhooks/resend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExosomesRoute = ExosomesRouteImport.update({
  id: '/exosomes',
  path: '/exosomes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescribersRoute = PrescribersRouteImport.update({
  id: '/prescribers',
  path: '/prescribers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgeConfirmRoute = ApiPublicAgeConfirmRouteImport.update({
  id: '/api/public/age-confirm',
  path: '/api/public/age-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailQueueProcessRoute = ApiEmailQueueProcessRouteImport.update({
  id: '/api/email/queue/process',
  path: '/api/email/queue/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailWebhooksResendRoute = ApiEmailWebhooksResendRouteImport.update({
  id: '/api/email/webhooks/resend',
  path: '/api/email/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/exosomes': typeof ExosomesRoute
  '/faq': typeof FaqRoute
  '/prescribers': typeof PrescribersRoute
  '/products': typeof ProductsRoute
  '/supplies': typeof SuppliesRoute
  '/training': typeof TrainingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/age-confirm': typeof ApiPublicAgeConfirmRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/webhooks/resend': typeof ApiEmailWebhooksResendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/exosomes': typeof ExosomesRoute
  '/faq': typeof FaqRoute
  '/prescribers': typeof PrescribersRoute
  '/products': typeof ProductsRoute
  '/supplies': typeof SuppliesRoute
  '/training': typeof TrainingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/age-confirm': typeof ApiPublicAgeConfirmRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/webhooks/resend': typeof ApiEmailWebhooksResendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/exosomes': typeof ExosomesRoute
  '/faq': typeof FaqRoute
  '/prescribers': typeof PrescribersRoute
  '/products': typeof ProductsRoute
  '/supplies': typeof SuppliesRoute
  '/training': typeof TrainingRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/age-confirm': typeof ApiPublicAgeConfirmRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/api/email/webhooks/resend': typeof ApiEmailWebhooksResendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliates'
    | '/compliance'
    | '/contact'
    | '/exosomes'
    | '/faq'
    | '/prescribers'
    | '/products'
    | '/supplies'
    | '/training'
    | '/email/unsubscribe'
    | '/api/public/age-confirm'
    | '/api/email/queue/process'
    | '/api/email/webhooks/resend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliates'
    | '/compliance'
    | '/contact'
    | '/exosomes'
    | '/faq'
    | '/prescribers'
    | '/products'
    | '/supplies'
    | '/training'
    | '/email/unsubscribe'
    | '/api/public/age-confirm'
    | '/api/email/queue/process'
    | '/api/email/webhooks/resend'
  id:
    | '__root__'
    | '/'
    | '/affiliates'
    | '/compliance'
    | '/contact'
    | '/exosomes'
    | '/faq'
    | '/prescribers'
    | '/products'
    | '/supplies'
    | '/training'
    | '/email/unsubscribe'
    | '/api/public/age-confirm'
    | '/api/email/queue/process'
    | '/api/email/webhooks/resend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliatesRoute: typeof AffiliatesRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  ExosomesRoute: typeof ExosomesRoute
  FaqRoute: typeof FaqRoute
  PrescribersRoute: typeof PrescribersRoute
  ProductsRoute: typeof ProductsRoute
  SuppliesRoute: typeof SuppliesRoute
  TrainingRoute: typeof TrainingRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicAgeConfirmRoute: typeof ApiPublicAgeConfirmRoute
  ApiEmailQueueProcessRoute: typeof ApiEmailQueueProcessRoute
  ApiEmailWebhooksResendRoute: typeof ApiEmailWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exosomes': {
      id: '/exosomes'
      path: '/exosomes'
      fullPath: '/exosomes'
      preLoaderRoute: typeof ExosomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescribers': {
      id: '/prescribers'
      path: '/prescribers'
      fullPath: '/prescribers'
      preLoaderRoute: typeof PrescribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/age-confirm': {
      id: '/api/public/age-confirm'
      path: '/api/public/age-confirm'
      fullPath: '/api/public/age-confirm'
      preLoaderRoute: typeof ApiPublicAgeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/queue/process': {
      id: '/api/email/queue/process'
      path: '/api/email/queue/process'
      fullPath: '/api/email/queue/process'
      preLoaderRoute: typeof ApiEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/webhooks/resend': {
      id: '/api/email/webhooks/resend'
      path: '/api/email/webhooks/resend'
      fullPath: '/api/email/webhooks/resend'
      preLoaderRoute: typeof ApiEmailWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliatesRoute: AffiliatesRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  ExosomesRoute: ExosomesRoute,
  FaqRoute: FaqRoute,
  PrescribersRoute: PrescribersRoute,
  ProductsRoute: ProductsRoute,
  SuppliesRoute: SuppliesRoute,
  TrainingRoute: TrainingRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicAgeConfirmRoute: ApiPublicAgeConfirmRoute,
  ApiEmailQueueProcessRoute: ApiEmailQueueProcessRoute,
  ApiEmailWebhooksResendRoute: ApiEmailWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
